from modules.kubernetes.openebs.cstorpoolclusters import zabbixDiscoveryCstorpoolclusters, zabbixItemsCstorpoolclusters
from modules.kubernetes.openebs.cstorpoolinstances import zabbixDiscoveryCstorpoolinstances, zabbixItemsCstorpoolinstances
